### PR TITLE
Convert hash keys back to strings if Cinchize is loaded

### PR DESCRIPTION
**Pull request by s0ph0s-dog**
This pull request adds compatibility for usage with Cinchize, a Cinch plugin system. It does this by detecting if `Cinchize::VERSION` is defined, and converting the channel names in the config hash back to strings from keys.  
This PR adds one new private method: `Cinch::Plugin::Cooldowns#self.hash_keys_to_strs` which accepts one argument, a hash, and converts all of its keys to strings, non-recursively.  
This PR fixes issue #1.

### CODE REVIEW

**Comment by bhaberer** [comment]
Thanks for your assistance in tracking down the issue! 

However,  I'm not sure that this is the best way to fix this issue. 

Looking over the issues, it seems that the best practice is to avoid adding one off code-cruft to handle an edge-case in another framework. 

Is there no way to fix this mis-handling of configuration values in upstream cinchize?

**If, and only if** that's not an option, I think a better path would be for me to transition cinch-cooldown to 1.2.0 and move to using symbols for all configuration values.

**Comment by s0ph0s-2** [comment]
In upstream Cinchize, [this function](https://github.com/netfeed/cinchize/blob/master/lib/cinchize.rb#L154) is called on the config array, which recursively converts all hash keys to symbols. It might be possible to add some sort of flag to the cinchize.yml file that instructs the function to stop converting the keys below that level, but that also seems like a crufty solution. I don't know what else depends on the keys being symbols, so I don't know what removing it would break.

**Comment by rikai** [comment]
As far as i can tell, there's no good reason for strings at all, and most other plugins do indeed use symbols  for configuration, and are faster to access, so my opinion would be that moving to using symbols would be the appropriate choice in any plugins currently using strings. :+1:

**Comment by bhaberer** [comment]
Yep, and I'll do this soon, been batting away a cold for the last couple
days.

**Comment by rikai** [comment]
No worries, priority should always be health! :)

**Pull request closed without merging**
